name: Agent Health Monitor
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  health:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run health check
        run: |
          python scripts/agent_health.py
          cat .llmstate/agent-health.jsonl || true
