 # Patch P0003: CI workflow to deploy and health-check the infra stack
 name: Infra Stack Deployment
 on:
   workflow_dispatch:

 jobs:
   deploy:
     runs-on: ubuntu-latest
     env:
       CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
       CLOUDFLARE_ZONE_ID:    ${{ secrets.CLOUDFLARE_ZONE_ID }}
     steps:
       - uses: actions/checkout@v4
       - name: Start Infra Stack
         run: |
           docker-compose up -d
       - name: Wait for Weaviate readiness
         run: |
           until curl -fsSk https://vector.pegasuswingman.com/v1/.well-known/ready; do sleep 5; done
       - name: Check MinIO health
         run: |
           curl -fsS https://storage.pegasuswingman.com/minio/health/live
       - name: Check Traefik dashboard
         run: |
           curl -fsS https://traefik.pegasuswingman.com/dashboard/